name: Unit Tests

on: [push]

jobs:
  unit_tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            python: python3
            pip_arg: ""
          - os: macos-14
            python: python3
            pip_arg: ""
          - os: windows-2019
            python: python
            pip_arg: --user

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install Pip Dependencies
      shell: bash
      run: pip install ${{ matrix.pip_arg }} -r requirements.txt
    - name: Run Tests
      run: nosetests
    - name: Upload Coverage Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
